= Electromagnetic waves have inertia

An antenna emits waves of an inertial substance. Thus the waves travel
with the antenna. This is why the Michelson-Morley effect occurs.
There is nothing strange about the Michelson-Morley effect. It is the
most intuitively obvious thing ever, once an antenna is correctly
visualized.

If you believe in photons and that they have momentum, then you must
accept that they would be a sufficient explanation for the
Michelson-Morley effect. Special Relativity would be
unnecessary.footnote:[I myself do not believe in photons as commonly
described, although I do believe electromagnetic material of some kind
is probably emitted in “quanta” due to resonance effects not yet
described. One thing I would like to do is to see if I can derive a
mass density for electromagnetic transmissions. Thus instead of “zero
rest mass” photons we would have a continuous material with a mass
density.]

I derive the transverse and longitudinal Doppler shifts. They are the
same as those derived with Special Relativity. The new system of
kinematics should be built around these Doppler shifts, because what
matters is when one has encounters with electromagnetic wavefronts.

I do not use “Observer and Frame of Reference” methods. I instead use
straightforward geometry, without assuming the existence of an
“Observer,” and not necessarily using any coordinate system. Thus the
kinematics is not a “relativity.” It is simply “kinematics.”

There is no hint of either time dilation or length
contraction.footnote:[That these distortions were probably fallacious
was already discovered by A.{nbsp}F. Kracklauer, who drew a Minkowski
diagram for the “Twin Paradox” in which there was no asymmetric aging.
(I will supply references later.) The “Twin Paradox” is physically
impossible, because the amount of aging difference depends on the
amount of _inertial_ motion! Which is ludicrous. The acceleration that
occurs at the pivot, which physics teachers emphasize, has no
quantitative role.]
